Repository open-telemetry/opentelemetry-ebpf-profiler, pull requests merged in 2024-09, with the labels that each got.

#114 design-docs: describe process and add examples
  design-docs/00000-example-docs/02612-process-manager-fileid-pid-split/README.md
  design-docs/00000-example-docs/04359-remove-bpf-hashing/README.md
  design-docs/00000-example-docs/04359-remove-bpf-hashing/known-trace-metrics.png
  design-docs/00000-example-docs/04359-remove-bpf-hashing/memcpy-cost.png
  design-docs/00000-example-docs/04359-remove-bpf-hashing/option2-ghidra-workload.png
  design-docs/00000-example-docs/04359-remove-bpf-hashing/option2-idle-workload.png
  design-docs/00000-example-docs/04359-remove-bpf-hashing/trace-pipe-reworked.drawio.svg
  design-docs/00000-example-docs/04359-remove-bpf-hashing/trace-pipe.drawio.svg
  design-docs/00000-example-docs/README.md
  design-docs/00000-templates/long-form-design-doc-template.md
  design-docs/00000-templates/short-form-design-doc-template.md
  design-docs/README.md
Labels: documentation

#156 Move type SourceLineno to libpf
  interpreter/hotspot/method.go
  interpreter/hotspot/unsigned5.go
  interpreter/nodev8/v8.go
  interpreter/perl/instance.go
  interpreter/php/instance.go
  interpreter/python/python.go
  interpreter/ruby/ruby.go
  libpf/libpf.go
  processmanager/manager_test.go
  reporter/iface.go
  reporter/otlp_reporter.go
  tools/coredump/coredump.go
  tracer/ebpf_integration_test.go
  util/util.go
Labels: cleanup

#133 Rename struct traceFramesCounts -> traceEvents
  reporter/otlp_reporter.go
Labels: cleanup

#165 Readme: provide new version of devfiler
  README.md
Labels: documentation

#162 Update deps and licenses
  LICENSES/golang.org/x/arch/arm64/arm64asm/LICENSE
  LICENSES/golang.org/x/exp/constraints/LICENSE
  LICENSES/golang.org/x/sync/errgroup/LICENSE
  LICENSES/golang.org/x/sys/unix/LICENSE
  cli_flags.go
  go.mod
  go.sum
  main.go
  tracer/ebpf_integration_test.go
  tracer/tracer.go
Labels: cleanup, dependencies
