Repository open-telemetry/opentelemetry-ebpf-profiler, pull requests merged in 2024-10, with the labels that each got.

#179 Update README
  Makefile
  README.md
  cli_flags.go
Labels: documentation

#144 [RFC] design doc: proposal for off-cpu profiling
  design-docs/00001-off-cpu-profiling/README.md
Labels: design-document

#214 Metrics: Drop unused reporter metrics
  metrics/ids.go
  metrics/metrics.json
  reporter/metrics.go
Labels: cleanup
