Repository open-telemetry/opentelemetry-ebpf-profiler, pull requests merged in 2024-07, with the labels that each got.

#53 Properly populate reported mappings with ELF VAs
  libpf/trace.go
  processmanager/manager.go
  processmanager/processinfo.go
  processmanager/types.go
  reporter/otlp_reporter.go
  tracer/tracer.go
Labels: enhancement

#58 CI: extract common logic into setup action
  .github/workflows/env/action.yml
  .github/workflows/unit-test-on-pull-request.yml
Labels: enhancement

#55 Extend reporter interface to support symbol upload
  interpreter/dotnet/instance.go
  processmanager/manager_test.go
  processmanager/processinfo.go
  reporter/iface.go
  reporter/otlp_reporter.go
  tools/coredump/coredump.go
  tracer/ebpf_integration_test.go
  tracer/tracer.go
Labels: enhancement

#65 New package env to reduce global vars
  config/config.go
  config/config_test.go
  env/env.go
  env/env_test.go
  hostmetadata/collector.go
  main.go
Labels: cleanup

#66 Make private flags public
  cli_flags.go
  cli_flags_internal.go
Labels: cleanup

#67 Avoid global variables for flag variables
  cli_flags.go
  main.go
Labels: cleanup

#68 Cleanup code in mainWithExitCode()
  main.go
Labels: cleanup

#70 Move tags validation to hostmeta
  cli_flags.go
  config/config.go
  config/config_test.go
  hostmetadata/host/host.go
  hostmetadata/host/host_test.go
  main.go
Labels: cleanup

#69 Rename env/ to platform/
  hostmetadata/collector.go
  main.go
  platform/platform.go
  platform/platform_test.go
Labels: cleanup

#79 Fix kernel version check to >= 4.19
  main.go
Labels: bug

#82 Fix data race in reporter
  reporter/otlp_reporter.go
Labels: bug

#83 Fix sample aggregation in reporter
  reporter/otlp_reporter.go
Labels: bug

#84 Remove global config
  config/config.go
  config/config_test.go
  hostmetadata/agent/agent.go
  hostmetadata/collector.go
  hostmetadata/host/host.go
  hostmetadata/host/host_test.go
  main.go
  processmanager/execinfomanager/manager.go
  processmanager/manager.go
  processmanager/manager_test.go
  reporter/config.go
  reporter/otlp_reporter.go
  reporter/times.go
  times/times.go
  tools/coredump/coredump.go
  tracehandler/tracehandler.go
  tracehandler/tracehandler_test.go
  tracer/ebpf_integration_test.go
  tracer/systemconfig.go
  tracer/tracer.go
  tracer/types/parse.go
  tracer/types/parse_test.go
Labels: cleanup

#98 Switch to math/rand/v2
  libpf/convenience.go
  pacmask/pacmask_arm64.go
  processmanager/manager_test.go
  testsupport/io.go
  tracer/tracer.go
Labels: cleanup

#97 Add helper function getHostnameAndSourceIP()
  helpers.go
  main.go
Labels: cleanup
