Repository open-telemetry/opentelemetry-ebpf-profiler, pull requests merged in 2025-01, with the labels that each got.

#290 Fix cross-compilation (#282)
  Makefile
Labels: bug

#295 metrics: update package documentation
  metrics/doc.go
Labels: documentation, cleanup

#304 README: drop make target docker-image as pre requirement
  README.md
Labels: documentation

#319 reporter/collector: fix reporting issue
  reporter/collector_reporter.go
  reporter/otlp_reporter.go
Labels: bug
